version: '2'

services:
  myapp:
    container_name: application
    image: 'babyfoot-manager'
    ports:
      - 9000:9000
      - 9001:9001
    volumes:
      - ./app:/usr/src/myapp
      - /var/run/php/php8.1-fpm.sock
    depends_on:
      - mysql
  mysql:
    container_name: mysql
    image: 'mysql:latest'
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_HOST: mysql
    ports:
      - 3306:3306
  adminer:
    container_name: adminer
    image: adminer
    restart: always
    ports:
      - 8080:8080
  nginx:
    container_name: nginx
    image: 'nginx:latest'
    depends_on:
      - myapp
    ports:
      - 80:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./app:/usr/src/myapp
      - /var/run/php/php8.1-fpm.sock